### ISSUE TITLE
empty folders

### ISSUE THREAD

**Issue by AngryBeaver** [hakubo/gulp-folders#3]
if the pathToFolder does not have any subfolders the gulp task will throw an error. can it just do nothing and behaves normal so other gulp task depend on this can just run through ? 

gulp.task('task', folder(pathToFolder, function(folder){

**Comment by hakubo** [comment]
If pathToFolder is a path to a folder with no sub folders
`function(folder){` won't even run

I can't find any error in there now, apart from that gulp does not know when this `task` finishes
but since gulp never waits for anything this does not brake much, but I'll try to fix that anyway.

**Comment by AngryBeaver** [comment]
I just noticed that my task chain isnt running through when the folder for $folders is empty. So it could perfecly be the no error at all but not finishing thing you discovered. 

thx for looking into it.

**Comment by hakubo** [comment]
Cool, new version just got published. Let me know if that works for you. 
Closing now :)

Have a nice weekend!
